using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace MagicAppGen.Services;

/// <summary>One starter project template: a description plus the files it drops
/// into a new project folder.</summary>
public sealed record ProjectTemplate(
    string Id,
    string Title,
    string Language,
    string Summary,
    IReadOnlyDictionary<string, string> Files)
{
    /// <summary>The file the editor should open after scaffolding.</summary>
    public string MainFile => Files.Keys.First(f => !f.EndsWith(".manifest") && !f.EndsWith(".md"));
}

/// <summary>The catalog behind "New Project → From Template" and the AI's
/// <c>ListTemplates</c>/<c>ScaffoldProject</c> kernel functions. Every C#
/// template compiles under bflat <c>--stdlib:zero</c>: no static reference
/// fields, no <c>object[]</c> element stores, no <c>ToString()</c>/concat.</summary>
public static class ProjectTemplates
{
    public static IReadOnlyList<ProjectTemplate> All { get; } = Build();

    public static ProjectTemplate? Find(string id) =>
        All.FirstOrDefault(t => string.Equals(t.Id, id, StringComparison.OrdinalIgnoreCase));

    /// <summary>Write a template's files into <paramref name="dir"/> (existing
    /// files are left alone). Returns the path of the main source file.</summary>
    public static string Scaffold(ProjectTemplate t, string dir, string appName)
    {
        Directory.CreateDirectory(dir);
        foreach (var (name, body) in t.Files)
        {
            var path = Path.Combine(dir, name);
            if (File.Exists(path)) continue;
            File.WriteAllText(path, body.Replace("__APPNAME__", appName));
        }
        return Path.Combine(dir, t.MainFile);
    }

    static string Manifest(string id, string name, string type, string lang) => $$"""
    {
      "id": "com.example.{{id}}",
      "name": "{{name}}",
      "type": "{{type}}",
      "language": "{{lang}}",
      "version": "0.1.0",
      "permissions": [],
      "theme": "system"
    }
    """;

    static string Readme(string title, string how) => $"""
    # __APPNAME__ — {title}

    Generated by **MagicAppGen** (Jack - The Code Bender) for Buitenzorg OS,
    made by Gravicode Studios, led by Kang Fadhil.

    ## Build & run

    {how}

    C# apps are compiled with bflat `--stdlib:zero` plus the `bzstart.rs` shim
    (see `scripts/build-hello-csharp.ps1`), so they run in ring 3 with no GC.
    Keep the zerolib rules in mind: no static reference fields, no
    method-group→delegate conversions, no storing references into `object[]`
    elements, and no `new string()`/`ToString()`/string concatenation.
    """;

    static List<ProjectTemplate> Build()
    {
        var list = new List<ProjectTemplate>();

        // ---- 1. console ----------------------------------------------------
        list.Add(new ProjectTemplate("console", "Console app", "C#",
            "Plain ring-3 C# program: Console.WriteLine + a MILESTONE marker.",
            new Dictionary<string, string>
            {
                ["main.cs"] = """
                // __APPNAME__ — console app for Buitenzorg OS.
                // Build: compile with bflat --stdlib:zero and link with bzstart.rs
                // (see scripts/build-hello-csharp.ps1), then run from the shell.

                using System;
                using System.Runtime.InteropServices;

                class Program
                {
                    [DllImport("*")] static extern unsafe void bz_write(byte* buf, ulong len);

                    static int Add(int a, int b) => a + b;

                    // zerolib has no ToString()/string concat: format digits by hand
                    // into a stackalloc'd byte buffer and write it out directly.
                    static unsafe void Line(string label, int value)
                    {
                        byte* buf = stackalloc byte[96];
                        int i = 0;
                        for (int k = 0; k < label.Length && i < 80; k++) buf[i++] = (byte)label[k];
                        if (value < 0) { buf[i++] = (byte)'-'; value = -value; }
                        if (value == 0) buf[i++] = (byte)'0';
                        else
                        {
                            byte* d = stackalloc byte[12];
                            int j = 0;
                            while (value > 0 && j < 12) { d[j++] = (byte)('0' + (value % 10)); value /= 10; }
                            while (j > 0) buf[i++] = d[--j];
                        }
                        buf[i++] = (byte)'\n';
                        bz_write(buf, (ulong)i);
                    }

                    static void Main()
                    {
                        Console.WriteLine("__APPNAME__: halo dari ring 3!");

                        int total = 0;
                        for (int i = 1; i <= 5; i++) total = Add(total, i);
                        Line("__APPNAME__: 1..5 = ", total);

                        Console.WriteLine(total == 15
                            ? "MILESTONE: APP OK"
                            : "MILESTONE: APP FAIL");
                    }
                }
                """,
                ["app.manifest"] = Manifest("consoleapp", "__APPNAME__", "console", "csharp"),
                ["README.md"] = Readme("console app",
                    "Build the OS image (`scripts/build.ps1`), then `run __APPNAME__` in the shell."),
            }));

        // ---- 2. desktop-ui -------------------------------------------------
        list.Add(new ProjectTemplate("desktop-ui", "Desktop app (Buitenzorg.UI)", "C#",
            "A retained-mode window: StackPanel + TextBlock + Button + CheckBox, composited by UIHost.",
            new Dictionary<string, string>
            {
                ["main.cs"] = """
                // __APPNAME__ — desktop app for Buitenzorg OS (Buitenzorg.UI).
                // Compile together with bzui.cs + bzgfx.cs.

                using System;
                using Buitenzorg.Drawing;
                using Buitenzorg.UI;

                class Program
                {
                    static void Main()
                    {
                        Console.WriteLine("__APPNAME__: membuka jendela...");
                        Font font = Font.Default();
                        UIHost host = new UIHost("__APPNAME__", 320, 200);

                        StackPanel root = new StackPanel();
                        root.Padding = 12; root.Spacing = 10;
                        root.Background = new Color(0xFF1C2028);

                        TextBlock title = new TextBlock("__APPNAME__", font);
                        title.Foreground = Color.White;

                        TextBlock hint = new TextBlock("Dibuat dengan MagicAppGen", font);
                        hint.Foreground = new Color(0xFF9AA0AA);

                        Button go = new Button("Klik saya", font);
                        go.Height = 32; go.Tag = 1;

                        CheckBox chk = new CheckBox("Aktifkan fitur", font);

                        root.Add(title); root.Add(hint); root.Add(go); root.Add(chk);
                        host.Root = root;
                        host.Layout();
                        host.Render(new Color(0xFF1C2028));
                        host.Present();

                        // Interactive only when launched from the desktop shell;
                        // during the headless boot demo bz_is_interactive() is 0.
                        Console.WriteLine("MILESTONE: APP OK");
                    }
                }
                """,
                ["app.manifest"] = Manifest("desktopapp", "__APPNAME__", "desktop", "csharp"),
                ["README.md"] = Readme("desktop app",
                    "Compile `main.cs` with `bzui.cs` + `bzgfx.cs`, embed the ELF, then `run __APPNAME__`."),
            }));

        // ---- 3. drawing ----------------------------------------------------
        list.Add(new ProjectTemplate("drawing", "Drawing scene (Buitenzorg.Drawing)", "C#",
            "Software-renders a scene into a Bitmap (gradient, rounded rect, shadow, AA circle) and blits it.",
            new Dictionary<string, string>
            {
                ["main.cs"] = """
                // __APPNAME__ — Buitenzorg.Drawing scene, blitted to a window.
                // Compile together with bzgfx.cs (and bzui.cs for Window/Font).

                using System;
                using Buitenzorg.Drawing;
                using Buitenzorg.UI;

                class Program
                {
                    static void Main()
                    {
                        const int W = 360, H = 240;
                        Console.WriteLine("__APPNAME__: menggambar...");

                        Bitmap bmp = new Bitmap(W, H);
                        Graphics g = new Graphics(bmp);
                        Font font = Font.Default();

                        g.FillGradientV(0, 0, W, H, new Color(0xFF20304A), new Color(0xFF101820));
                        g.DrawShadow(20, 20, 200, 90, 12, 6, 90);
                        g.FillRoundedGradientV(20, 20, 200, 90, 12, new Color(0xFF3A78D8), new Color(0xFF2050A0));
                        g.DrawString(font, "__APPNAME__", Color.White, 36, 56);
                        g.FillCircleAA(new Color(0xFFE0A030), 290, 70, 34);
                        g.DrawLine(new Color(0xFF8890A0), 20, 140, W - 20, 140, 2);

                        Window win = Window.Create("__APPNAME__", W, H);
                        win.Blit(bmp);
                        win.Present();

                        Console.WriteLine("MILESTONE: APP OK");
                    }
                }
                """,
                ["app.manifest"] = Manifest("drawingapp", "__APPNAME__", "desktop", "csharp"),
                ["README.md"] = Readme("drawing scene",
                    "Compile `main.cs` with `bzgfx.cs` + `bzui.cs`, embed the ELF, then `run __APPNAME__`."),
            }));

        // ---- 4. game -------------------------------------------------------
        list.Add(new ProjectTemplate("game", "Game board (custom UIElement)", "C#",
            "A 4x4 board rendered by a custom UIElement with a move engine — the 2048 shape.",
            new Dictionary<string, string>
            {
                ["main.cs"] = """
                // __APPNAME__ — grid game for Buitenzorg OS.
                // A custom UIElement renders the board; the engine is plain C#.
                // Compile together with bzui.cs + bzgfx.cs.

                using System;
                using Buitenzorg.Drawing;
                using Buitenzorg.UI;

                sealed class Board : UIElement
                {
                    // Flat value-type array: never an array of references (stelem.ref faults).
                    public readonly int[] Cells = new int[16];
                    Font _font;
                    readonly char[] _num = new char[6];

                    public Board(Font f) { _font = f; }

                    public override void Measure(int aw, int ah)
                    { DesiredW = Width >= 0 ? Width : 260; DesiredH = Height >= 0 ? Height : 260; }

                    // Slide+merge one row to the left; returns true if anything moved.
                    public bool SlideRow(int row)
                    {
                        int b = row * 4;
                        bool moved = false;
                        for (int pass = 0; pass < 3; pass++)
                            for (int i = 0; i < 3; i++)
                                if (Cells[b + i] == 0 && Cells[b + i + 1] != 0)
                                { Cells[b + i] = Cells[b + i + 1]; Cells[b + i + 1] = 0; moved = true; }
                        for (int i = 0; i < 3; i++)
                            if (Cells[b + i] != 0 && Cells[b + i] == Cells[b + i + 1])
                            {
                                Cells[b + i] *= 2; Cells[b + i + 1] = 0; moved = true;
                                for (int j = i + 1; j < 3; j++) { Cells[b + j] = Cells[b + j + 1]; Cells[b + j + 1] = 0; }
                            }
                        return moved;
                    }

                    static Color TileColor(int v) => v switch
                    {
                        0 => new Color(0xFF2A2F3A),
                        2 => new Color(0xFF4A5568),
                        4 => new Color(0xFF3A78D8),
                        8 => new Color(0xFF2FA36B),
                        16 => new Color(0xFFE0A030),
                        _ => new Color(0xFFE0503C),
                    };

                    public override void Render(Graphics g)
                    {
                        if (!Visible) return;
                        g.FillRoundedRectangle(new Color(0xFF1A1E26), X, Y, W, H, 10);
                        int cell = (W - 10) / 4;
                        for (int r = 0; r < 4; r++)
                            for (int c = 0; c < 4; c++)
                            {
                                int v = Cells[r * 4 + c];
                                int x = X + 5 + c * cell, y = Y + 5 + r * cell;
                                g.FillRoundedRectangle(TileColor(v), x + 3, y + 3, cell - 6, cell - 6, 8);
                                if (v == 0) continue;
                                int n = 0, t = v;
                                while (t > 0) { _num[n++] = (char)('0' + t % 10); t /= 10; }
                                for (int i = 0; i < n / 2; i++) { char tmp = _num[i]; _num[i] = _num[n - 1 - i]; _num[n - 1 - i] = tmp; }
                                g.DrawChars(_font, _num, n, Color.White,
                                            x + cell / 2 - n * 4, y + cell / 2 - 4);
                            }
                    }
                }

                class Program
                {
                    static void Main()
                    {
                        Console.WriteLine("__APPNAME__: papan permainan...");
                        Font font = Font.Default();
                        UIHost host = new UIHost("__APPNAME__", 280, 320);

                        StackPanel root = new StackPanel();
                        root.Padding = 10; root.Spacing = 8;
                        root.Background = new Color(0xFF141820);

                        TextBlock title = new TextBlock("__APPNAME__", font);
                        title.Foreground = Color.White;

                        Board board = new Board(font);
                        board.Width = 260; board.Height = 260;
                        board.Cells[0] = 2; board.Cells[1] = 2; board.Cells[2] = 4; board.Cells[3] = 4;

                        root.Add(title); root.Add(board);
                        host.Root = root;
                        host.Layout();

                        bool moved = board.SlideRow(0);
                        bool ok = moved && board.Cells[0] == 4 && board.Cells[1] == 8;

                        host.Render(new Color(0xFF141820));
                        host.Present();
                        Console.WriteLine(ok ? "MILESTONE: APP OK" : "MILESTONE: APP FAIL");
                    }
                }
                """,
                ["app.manifest"] = Manifest("gameapp", "__APPNAME__", "desktop", "csharp"),
                ["README.md"] = Readme("grid game",
                    "Compile `main.cs` with `bzui.cs` + `bzgfx.cs`, embed the ELF, then `run __APPNAME__`."),
            }));

        // ---- 5. audio ------------------------------------------------------
        list.Add(new ProjectTemplate("audio", "Audio app (Buitenzorg.Audio)", "C#",
            "Reads the AC'97 mixer, round-trips the volume, and plays a tone.",
            new Dictionary<string, string>
            {
                ["main.cs"] = """
                // __APPNAME__ — audio app for Buitenzorg OS (AC'97 via Buitenzorg.Audio).
                // Compile together with bzaudio.cs.

                using System;
                using Buitenzorg.Audio;

                class Program
                {
                    static void Main()
                    {
                        Console.WriteLine("__APPNAME__: menguji mixer...");

                        AudioInfo info = Mixer.GetInfo();
                        bool ok = info.Present && info.SampleRate == 48000 && info.Channels == 2;

                        Mixer.SetVolume(40);
                        if (Mixer.GetVolume() != 40) ok = false;

                        // A short C-major arpeggio: Beep(frequencyHz, durationMs).
                        Mixer.Beep(262, 120);
                        Mixer.Beep(330, 120);
                        Mixer.Beep(392, 120);
                        Mixer.Beep(523, 200);

                        Console.WriteLine(ok ? "MILESTONE: APP OK" : "MILESTONE: APP FAIL");
                    }
                }
                """,
                ["app.manifest"] = Manifest("audioapp", "__APPNAME__", "desktop", "csharp"),
                ["README.md"] = Readme("audio app",
                    "Compile `main.cs` with `bzaudio.cs`, embed the ELF, then `run __APPNAME__`."),
            }));

        // ---- 6-8. polyglot -------------------------------------------------
        list.Add(new ProjectTemplate("js", "JavaScript app (polyglot runtime)", "JavaScript",
            "Runs on the in-kernel interpreter: shell `js main.js`.",
            new Dictionary<string, string>
            {
                ["main.js"] = """
                // __APPNAME__ — JavaScript app for Buitenzorg (v0.14 "Babel" runtime).
                // Run from the shell: `script js main.js` (or `js main.js`).

                function fib(n) {
                  if (n < 2) return n;
                  return fib(n - 1) + fib(n - 2);
                }

                console.log("__APPNAME__: fib(10) = " + fib(10));

                let total = 0;
                for (let i = 1; i <= 5; i = i + 1) total = total + i;
                console.log("__APPNAME__: 1..5 = " + total);
                """,
                ["app.manifest"] = Manifest("jsapp", "__APPNAME__", "console", "javascript"),
                ["README.md"] = Readme("JavaScript app", "From the shell: `js main.js`."),
            }));

        list.Add(new ProjectTemplate("ts", "TypeScript app (polyglot runtime)", "TypeScript",
            "Transpiled in-kernel (annotations stripped) then interpreted: shell `ts main.ts`.",
            new Dictionary<string, string>
            {
                ["main.ts"] = """
                // __APPNAME__ — TypeScript app for Buitenzorg (v0.14 "Babel" runtime).
                // The kernel strips interface/type/: Type annotations, then interprets.
                // Run from the shell: `script ts main.ts` (or `ts main.ts`).

                interface Point { x: number; y: number; }

                function dist2(a: Point, b: Point): number {
                  let dx: number = a.x - b.x;
                  let dy: number = a.y - b.y;
                  return dx * dx + dy * dy;
                }

                console.log("__APPNAME__: d2 = " + dist2({ x: 0, y: 0 }, { x: 3, y: 4 }));
                """,
                ["app.manifest"] = Manifest("tsapp", "__APPNAME__", "console", "typescript"),
                ["README.md"] = Readme("TypeScript app", "From the shell: `ts main.ts`."),
            }));

        list.Add(new ProjectTemplate("python", "Python app (polyglot runtime)", "Python",
            "Indentation-based subset interpreted in-kernel: shell `py main.py`.",
            new Dictionary<string, string>
            {
                ["main.py"] = """
                # __APPNAME__ — Python app for Buitenzorg (v0.14 "Babel" runtime).
                # Run from the shell: `script py main.py` (or `py main.py`).

                def fib(n):
                    if n < 2:
                        return n
                    return fib(n - 1) + fib(n - 2)

                print("__APPNAME__: fib(10) =", fib(10))

                total = 0
                for i in range(1, 6):
                    total = total + i

                print("__APPNAME__: 1..5 =", total)
                """,
                ["app.manifest"] = Manifest("pyapp", "__APPNAME__", "console", "python"),
                ["README.md"] = Readme("Python app", "From the shell: `py main.py`."),
            }));

        return list;
    }
}
